export const MODULE_REGISTRY = [
  { key: "dashboard",         label: "Dashboard",             group: "Home" },
  { key: "ess",               label: "ESS Portal",            group: "Home" },
  { key: "employees",         label: "Employees",             group: "Workforce" },
  { key: "org-chart",         label: "Org Chart",             group: "Workforce" },
  { key: "departments",       label: "Departments",           group: "Workforce" },
  { key: "branches",          label: "Branches",              group: "Workforce" },
  { key: "designations",      label: "Designations",          group: "Workforce" },
  { key: "recruitment",       label: "Recruitment",           group: "Talent Acquisition" },
  { key: "pre-onboarding",    label: "Pre-Onboarding",        group: "Talent Acquisition" },
  { key: "onboarding",        label: "Onboarding",            group: "Talent Acquisition" },
  { key: "shifts",            label: "Shifts",                group: "Time & Attendance" },
  { key: "attendance",        label: "Attendance",            group: "Time & Attendance" },
  { key: "leave",             label: "Leave",                 group: "Time & Attendance" },
  { key: "work-permissions",  label: "Permissions",           group: "Time & Attendance" },
  { key: "wfh",               label: "Work From Home",        group: "Time & Attendance" },
  { key: "shift-change",      label: "Shift Change",          group: "Time & Attendance" },
  { key: "approvals",         label: "Approvals Hub",         group: "Time & Attendance" },
  { key: "payroll",           label: "Payroll",               group: "Payroll" },
  { key: "performance",       label: "Performance",           group: "Performance" },
  { key: "helpdesk",          label: "Helpdesk",              group: "Employee Services" },
  { key: "documents",         label: "Documents",             group: "Employee Services" },
  { key: "expense-claims",    label: "Expense Claims",        group: "Employee Services" },
  { key: "communications",    label: "Communications",        group: "Employee Services" },
  { key: "exit",              label: "Exit & Offboarding",    group: "Separation" },
  { key: "analytics",         label: "Analytics",             group: "Insights" },
  { key: "reports",           label: "Reports",               group: "Insights" },
  { key: "users",             label: "Users",                 group: "Administration" },
  { key: "roles-permissions", label: "Roles & Permissions",   group: "Administration" },
  { key: "audit-logs",        label: "Audit Logs",            group: "Administration" },
  { key: "system-config",     label: "System Configuration",  group: "Administration" },
  { key: "api-keys",          label: "API Keys",              group: "Administration" },
  { key: "billing",           label: "Billing & Subscription",group: "Administration" },
] as const;

export type ModuleKey = (typeof MODULE_REGISTRY)[number]["key"];

export const PERMISSION_ACTIONS = [
  "view", "create", "edit", "delete", "approve",
  "export", "print", "reports", "settings", "admin",
] as const;
export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];

export type PermissionMap = Partial<Record<string, PermissionAction[]>>;

const ALL = [...PERMISSION_ACTIONS] as PermissionAction[];
const HR_ACTIONS: PermissionAction[] = ["view", "create", "edit", "delete", "approve", "export", "print", "reports", "settings"];

export const DEFAULT_PERMISSIONS: Record<string, Record<string, PermissionAction[]>> = {
  customer_admin: Object.fromEntries(MODULE_REGISTRY.map((m) => [m.key, ALL])),

  hr_manager: {
    dashboard:          ["view"],
    ess:                ["view"],
    employees:          ["view", "create", "edit", "approve", "export", "print"],
    "org-chart":        ["view"],
    departments:        ["view", "create", "edit", "delete"],
    branches:           ["view", "create", "edit", "delete"],
    designations:       ["view", "create", "edit", "delete"],
    recruitment:        ["view", "create", "edit", "delete", "approve", "export"],
    "pre-onboarding":   ["view", "create", "edit", "approve"],
    onboarding:         ["view", "create", "edit", "approve"],
    shifts:             ["view", "create", "edit", "delete"],
    attendance:         ["view", "create", "edit", "approve", "export", "reports"],
    leave:              ["view", "create", "edit", "approve", "export", "reports"],
    "work-permissions": ["view", "create", "edit", "approve"],
    wfh:                ["view", "create", "edit", "approve"],
    "shift-change":     ["view", "create", "edit", "approve"],
    approvals:          ["view", "approve"],
    payroll:            ["view", "reports"],
    performance:        ["view", "create", "edit", "approve", "reports"],
    helpdesk:           ["view", "create", "edit", "approve", "reports"],
    documents:          ["view", "create", "edit", "delete", "print"],
    "expense-claims":   ["view", "create", "edit", "approve"],
    communications:     ["view", "create", "edit", "delete"],
    exit:               ["view", "create", "edit", "approve", "reports"],
    analytics:          ["view", "export"],
    reports:            ["view", "export", "print"],
    users:              ["view", "create", "edit"],
    "roles-permissions":["view", "edit"],
    "audit-logs":       ["view", "export"],
    "system-config":    ["view", "edit", "settings"],
    "api-keys":         [],
    billing:            [],
  },

  hr_executive: {
    dashboard:          ["view"],
    ess:                ["view"],
    employees:          ["view", "create", "edit"],
    "org-chart":        ["view"],
    departments:        ["view"],
    branches:           ["view"],
    designations:       ["view"],
    recruitment:        ["view", "create", "edit"],
    "pre-onboarding":   ["view", "create", "edit"],
    onboarding:         ["view", "create", "edit"],
    shifts:             ["view", "create", "edit"],
    attendance:         ["view", "create", "edit", "approve"],
    leave:              ["view", "create", "edit", "approve"],
    "work-permissions": ["view", "create", "edit", "approve"],
    wfh:                ["view", "create", "edit", "approve"],
    "shift-change":     ["view", "create", "edit", "approve"],
    approvals:          ["view", "approve"],
    payroll:            ["view"],
    performance:        ["view", "create", "edit"],
    helpdesk:           ["view", "create", "edit"],
    documents:          ["view", "create", "edit"],
    "expense-claims":   ["view", "edit", "approve"],
    communications:     ["view"],
    exit:               ["view", "create", "edit"],
    analytics:          ["view"],
    reports:            ["view"],
    users:              [],
    "roles-permissions":[],
    "audit-logs":       ["view"],
    "system-config":    [],
    "api-keys":         [],
    billing:            [],
  },

  hod: {
    dashboard:          ["view"],
    ess:                ["view"],
    employees:          ["view"],
    "org-chart":        ["view"],
    departments:        ["view"],
    branches:           ["view"],
    designations:       ["view"],
    recruitment:        ["view", "create", "approve"],
    "pre-onboarding":   ["view"],
    onboarding:         ["view", "approve"],
    shifts:             ["view"],
    attendance:         ["view", "approve"],
    leave:              ["view", "approve"],
    "work-permissions": ["view", "approve"],
    wfh:                ["view", "approve"],
    "shift-change":     ["view", "approve"],
    approvals:          ["view", "approve"],
    payroll:            [],
    performance:        ["view", "create", "edit", "approve"],
    helpdesk:           ["view", "create"],
    documents:          ["view"],
    "expense-claims":   ["view", "approve"],
    communications:     [],
    exit:               ["view", "approve"],
    analytics:          ["view"],
    reports:            ["view"],
    users:              [],
    "roles-permissions":[],
    "audit-logs":       [],
    "system-config":    [],
    "api-keys":         [],
    billing:            [],
  },

  payroll_admin: {
    dashboard:          ["view"],
    ess:                ["view"],
    employees:          ["view", "export"],
    "org-chart":        ["view"],
    departments:        ["view"],
    branches:           ["view"],
    designations:       ["view"],
    recruitment:        [],
    "pre-onboarding":   [],
    onboarding:         [],
    shifts:             ["view"],
    attendance:         ["view", "export", "reports"],
    leave:              ["view", "export", "reports"],
    "work-permissions": ["view"],
    wfh:                ["view"],
    "shift-change":     ["view"],
    approvals:          [],
    payroll:            ["view", "create", "edit", "delete", "approve", "export", "print", "reports"],
    performance:        [],
    helpdesk:           ["view", "create"],
    documents:          ["view"],
    "expense-claims":   ["view", "approve"],
    communications:     [],
    exit:               ["view"],
    analytics:          ["view"],
    reports:            ["view", "export", "print"],
    users:              [],
    "roles-permissions":[],
    "audit-logs":       [],
    "system-config":    [],
    "api-keys":         [],
    billing:            [],
  },

  employee: {
    dashboard:          ["view"],
    ess:                ["view"],
    employees:          [],
    "org-chart":        ["view"],
    departments:        [],
    branches:           [],
    designations:       [],
    recruitment:        [],
    "pre-onboarding":   [],
    onboarding:         ["view"],
    shifts:             ["view"],
    attendance:         ["view", "create"],
    leave:              ["view", "create"],
    "work-permissions": ["view", "create"],
    wfh:                ["view", "create"],
    "shift-change":     ["view", "create"],
    approvals:          [],
    payroll:            ["view", "print"],
    performance:        ["view", "create"],
    helpdesk:           ["view", "create"],
    documents:          ["view"],
    "expense-claims":   ["view", "create"],
    communications:     [],
    exit:               ["view", "create"],
    analytics:          [],
    reports:            [],
    users:              [],
    "roles-permissions":[],
    "audit-logs":       [],
    "system-config":    [],
    "api-keys":         [],
    billing:            [],
  },
};
